services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - keycloak
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    command:
      - start-dev
      - --proxy-headers=xforwarded
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

